# Generated by Django 5.2.17 on 2026-10-07 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pledges.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_number', models.CharField(default=pledges.models.generate_pledge_number, editable=False, max_length=36, unique=True)),
                ('pledge_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('redeemed_date', models.DateField(blank=True, editable=False, null=True)),
                ('cancelled_date', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='accounts.customer')),
            ],
            options={
                'ordering': ['-pledge_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('weight_grams', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('quantity', models.PositiveIntegerField()),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pledges.pledge')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['customer', 'pledge_date'], name='pledges_ple_custome_fcfc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['status', 'due_date'], name='pledges_ple_status_867b39_idx'),
        ),
        migrations.AddConstraint(
            model_name='pledge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gte', 0)), name='pledge_amount_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pledgeitem',
            constraint=models.UniqueConstraint(fields=('pledge', 'sequence'), name='unique_pledge_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='pledgeitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__gte', 0)), name='pledge_item_weight_nonnegative'),
        ),
    ]
