# Generated by Django 5.2.17 on 2026-10-08 01:58

import django.core.validators
import pledges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_date',
            field=models.DateField(default=pledges.models.nepal_today),
        ),
        migrations.AlterField(
            model_name='pledgeitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='pledgeitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='pledge_item_quantity_positive'),
        ),
    ]
