# Generated by Django 5.2.17 on 2026-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='gold_rate',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='billitem',
            name='material',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('GEMSTONE', 'Gemstone'), ('OTHER', 'Other')], default='GOLD', max_length=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='rate_unit',
            field=models.CharField(choices=[('g', 'Rs./g'), ('piece', 'Rs./piece'), ('carat', 'Rs./carat'), ('item', 'Rs./item')], default='g', max_length=10),
        ),
    ]
